name: CI/CD

on:
  push:

  pull_request:
    branches:
      - main

env:
  MIX_ENV: test

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version-file: .tool-versions
      #     cache: npm
      #     cache-dependency-path: assets/package-lock.json

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-
            ${{ runner.os }}-mix-

      - run: mix deps.clean --all
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: rm -rf priv/plts
      - run: mix dialyzer --plt

      - name: Save cache
        uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}

      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix check

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: test/reports/test-junit-report.xml
        if: always()
